---
engines:
  rubocop:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "app/controllers/api/docs/models/*.rb"
- "app/controllers/api/docs/*.rb"
- "spec/**/*"
