AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'Rakefile'
    - 'Capfile'
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/SpaceInsideStringInterpolation:
  Enabled: false

Rails/ActionFilter:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true
