AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'bin/capify'
    - 'bin/cap'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/SpaceInsideStringInterpolation:
  Enabled: false

Rails/ActionFilter:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/FileName:
  Enabled: false

