AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'bin/capify'
    - 'bin/cap'

Rails:
  Enabled: true

# Two spaces, no tabs (for indentation).
Style/IndentationWidth:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/SpaceInsideStringInterpolation:
  Enabled: false

Rails/ActionFilter:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/FileName:
  Enabled: false

# Enable this cop later
Style/FrozenStringLiteralComment:
  Enabled: false
