AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'bin/capify'
    - 'bin/cap'


Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/SpaceInsideStringInterpolation:
  Enabled: false

Rails/ActionFilter:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true
