AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'Rakefile'
    - 'Capfile'
    - 'lib/tasks/cucumber.rake'
    - 'lib/tasks/backup.rake'
    - 'config/backup.rb'
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading
