language: ruby
rvm:
  - 1.9.3
  - rbx-19mode
env:
  - ISOLATED=true
  - DB=postgresql

before_script:
  - "cp config/database.travis.yml config/database.yml"
  - "psql -c 'create database prometheus_test;' -U postgres >/dev/null"
