language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql

before_script:
  - gem update --system
  - gem --version
  - cp config/database.travis.yml config/database.yml
  - cp config/redis.yml.sample config/redis.yml
  - psql -c 'create database prometheus_test;' -U postgres
