# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f40b6cfc49b9d95225ffe01c7163a7ebd2e35cbed87e2928d9f0c51b59385bcdb06b2da12d1c8245fb89058d8c19770730ff81911be989814d9b621a723b556

test:
  secret_key_base: 0f40b6cfc49b9d95225ffe01c7163a7ebd2e35cbed87e2928d9f0c51b59385bcdb06b2da12d1c8245fb89058d8c19770730ff81911be989814d9b621a723b556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
