development:
  max_matches: 10000
  min_infix_len: 3
  mem_limit: 768M
  quiet_deltas: true
test:
  max_matches: 10000
  min_infix_len: 3
  mem_limit: 768M
  quiet_deltas: true
production:
  max_matches: 10000
  min_infix_len: 3
  mem_limit: 768M
  quiet_deltas: true
  pid_file: /home/prometheusapp/www/shared/tmp/searchd.pid
  indices_location: /home/prometheusapp/www/shared/db/sphinx
  configuration_file: /home/prometheusapp/www/shared/production.sphinx.conf
  binlog_path: /home/prometheusapp/www/shared/binlog
staging:
  max_matches: 10000
  min_infix_len: 3
  mem_limit: 768M
  quiet_deltas: true
